services:
  mongodb:
    image: mongo:8.2.4-noble
    container_name: mongo

    ports:
      - "27007:27017"

    volumes:
      - ./mongodb:/data/db

    networks:
      - backend

    restart: always


networks:
  backend:
